import type { Metadata } from "next";
import { Roboto, Montserrat } from "next/font/google";
import "./globals.css";
import { ModalCartItemsAdded } from "@/components/modalCartItemsAdded";
import AuthProvider from "@/providers/auth";
import ProviderContext from "@/context/Context";

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat'
});;

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${roboto.variable}`}>
      <body
        className="bg-gray-700 text-gray-200 "
      >
        <AuthProvider>
          <ProviderContext>
            <ModalCartItemsAdded />
            {children}
          </ProviderContext>
        </AuthProvider>
      </body>
    </html>
  );
}